# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NewGithubSearchIssueApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NewGithubSearchIssueApp
pod 'SnapKit'
pod 'RxSwift'
pod 'RxCocoa'
pod 'RxAlamofire'
  target 'NewGithubSearchIssueAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NewGithubSearchIssueAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
